/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package duan1.components;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;

import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author TAN PHAT
 */
public class Cards extends javax.swing.JPanel {

    /**
     * Creates new form Cards
     */
    public Cards() {
        initComponents();
        setOpaque(false);
    }

    public void setImg(String imageurl) {
        try {

            URL urls = new URL(imageurl);
//
//            ImageIcon icon = new ImageIcon(urls);

            ImgLable.setIcon(ImageProduct(urls));
        } catch (Exception ex) {
            Logger.getLogger(Cards.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

//    public BufferedImage crop(BufferedImage src) {
//        BufferedImage dest = new BufferedImage(getWidth(), getHeight(), BufferedImage.TYPE_INT_ARGB_PRE);
//        Graphics g = dest.getGraphics();
//        g.drawImage(src, 0, 0, getWidth(), getHeight(), getX(), getY(),getX() + getWidth(), getY() + getHeight(), null);
//        g.dispose();
//        return dest;
//    }
//    private Image createImageWithText(String src, int x, int y) {
//        BufferedImage bufferedImage = new BufferedImage(50, 50, BufferedImage.TYPE_INT_RGB);
//        Graphics g = bufferedImage.getGraphics();
//
//        g.drawString(src, x, y);
//
//        return bufferedImage;
//    }
//    private String bu (String src){
//        BufferedImage buf = new BufferedImage(20, 20, BufferedImage.TYPE_INT_ARGB);
//        Graphics g = buf.getGraphics();
//        
//         g.drawString(src, 20, 20);
//        return buf.toString() ;
//    }
    ImageIcon ImageProduct(URL src) {
        ImageIcon imacon = new ImageIcon(src);
        Image dadimage = imacon.getImage();
        Image modifiedDabImage = dadimage.getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
        imacon = new ImageIcon(modifiedDabImage);
        
        return imacon;
    }
    
    

    public void setName(String name) {
        ProductTitle.setText(name);
    }

    public void setPrice(Double price) {
        ProductPrice.setText(price.toString());
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImgLable = new javax.swing.JLabel();
        ProductPrice = new javax.swing.JLabel();
        ProductTitle = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        ProductPrice.setText("jLabel2");

        ProductTitle.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(ProductPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ImgLable, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(ProductPrice)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        this.setBackground(new Color(64, 64, 64));
    }//GEN-LAST:event_formMouseEntered

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        this.setBackground(new Color(217, 217, 217));
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgLable;
    private javax.swing.JLabel ProductPrice;
    private javax.swing.JLabel ProductTitle;
    // End of variables declaration//GEN-END:variables
}
