/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package duan1.components;

/**
 *
 * @author nhatsdevil
 */
public class HeaderBar extends javax.swing.JPanel {
    private Runnable goBackEvent;

    /**
     * Creates new form HeaderBar
     */
    public HeaderBar() {
        initComponents();
        init();
    }

    public void setTitle(String value) {
        lblTitle.setText(value);
    }

    public void onBack(Runnable func) {
        lead.setVisible(func != null);

        goBackEvent = func;
    }

    private void init() {
        lead.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lead = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        title = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        lead.setBackground(new java.awt.Color(255, 255, 255));
        lead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("<");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        lead.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 41, 50));

        add(lead, java.awt.BorderLayout.LINE_START);

        title.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblTitle.setText("SCREEN NAME");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(545, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(22, 22, 22))
        );

        add(title, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if(goBackEvent != null) goBackEvent.run();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel lead;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
