/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package duan1.components;

import java.awt.Color;
import java.awt.Font;
import java.util.function.Function;

import duan1.config.Config;

/**
 *
 * @author nhatsdevil
 */
public class SideBarItem extends javax.swing.JPanel {
    private Function<Integer, Void> onClickEvent;

    /**
     * Creates new form SideBarItem
     */
    public SideBarItem() {
        initComponents();
        init();
    }

    public void onClick(Function<Integer, Void> func) {
        onClickEvent = func;
    }

    public void setTitle(String title) {
        titleLbl.setText(title);
    }

    public void setIcon(String icon) {
        Font font = Config.FONT_IONICONS.deriveFont(20f);

        iconLbl.setFont(font);
        iconLbl.setText(icon);
    }

    public void setActive(Boolean active) {
        if(active) {
            iconLbl.setForeground(new Color(255, 255, 255));
            titleLbl.setForeground(new Color(255, 255, 255));
            activeBackground.setBackground(new Color(10, 132, 255, 255));
        }else{
            iconLbl.setForeground(new Color(176, 190, 197));
            titleLbl.setForeground(new Color(176, 190, 197));
            activeBackground.setBackground(new Color(18, 19, 26));
        }
    }

    private void init() {
        iconLbl.setForeground(new Color(176, 190, 197));
        titleLbl.setForeground(new Color(176, 190, 197));

        this.setOpaque(true);
        this.setBackground(new Color(18, 19, 26));

        // activeBackground.setOpaque(true);
        activeBackground.setBackground(new Color(18, 19, 26));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activeBackground = new duan1.components.PanelBoder();
        titleLbl = new javax.swing.JLabel();
        iconLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        activeBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        titleLbl.setText("MENU ITEM TITLE");
        activeBackground.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 15, -1, -1));

        iconLbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        iconLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLbl.setText("T");
        activeBackground.add(iconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 34, 32));

        add(activeBackground, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        onClickEvent.apply(0);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private duan1.components.PanelBoder activeBackground;
    private javax.swing.JLabel iconLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
