/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package duan1.components;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.awt.Font;

import javax.swing.JLabel;

import duan1.config.Config;
import duan1.controllers.user.UserController;
import duan1.models.user.UserModel;
import duan1.utils.WrapLayout;
import duan1.views.App;
import duan1.views.KhachHang;
import duan1.views.KhuyenMai;
import duan1.views.Login;
import duan1.views.NhanVien;
import duan1.views.SanPham;
import duan1.views.ThemHoaDon;

/**
 *
 * @author nhatsdevil
 */

class SMenuItem <V> {
    public String title;
    public String icon;
    public Class<V> view;
    public Boolean isBreak;

    public SMenuItem() {
        
    }

    public SMenuItem(String title, String icon, Class<V> view, Boolean isBreak) {
        this.title = title;
        this.icon = icon;
        this.view = view;
        this.isBreak = isBreak;
    }
}

public class SideBar extends javax.swing.JPanel {
    private ArrayList<SMenuItem> menuItems = new ArrayList<>();
    private UserController userController = new UserController();
    private App appContext;
    
    /**
     * Creates new form SideBar
     */
    public SideBar() {
        initComponents();
        initMenuItems();
    }

    public void setAppContext(App context) {
        this.appContext = context;
    }

    private void initMenuItems() {
        //Set app version
        appVersion.setText(Config.APP_VERSION);

        menuItemsGroup.setLayout(new WrapLayout(0, 0, 12));

        //Set User Info
        try {
            UserModel userInfo = userController.checkLogin();
            
            userNameLbl.setText(userInfo.name);
            emailLbl.setText(userInfo.email);
        } catch (Exception e1) {
            
        }
        
        //Create items
        menuItems.add(new SMenuItem<SideBarItem>("Bán Hàng", "", SideBarItem.class, true));
        menuItems.add(new SMenuItem<ThemHoaDon>("Đơn Hàng", "\uf292", ThemHoaDon.class, false));
        menuItems.add(new SMenuItem<SanPham>("Sản Phẩm", "\uf10e", SanPham.class, false));
        menuItems.add(new SMenuItem<KhuyenMai>("Khuyến Mãi", "\uf35b", KhuyenMai.class, false));
        menuItems.add(new SMenuItem<ThemHoaDon>("Thống Kê", "\uf21c", ThemHoaDon.class, false));
        menuItems.add(new SMenuItem<KhachHang>("Khách Hàng", "\uf2d7", KhachHang.class, false));
        menuItems.add(new SMenuItem<SideBarItem>("Quản Lý", "", SideBarItem.class, true));
        menuItems.add(new SMenuItem<NhanVien>("Nhân Viên", "\uf345", NhanVien.class, false));
        menuItems.add(new SMenuItem<ThemHoaDon>("Cài Đặt", "\uf377", ThemHoaDon.class, false));
        menuItems.add(new SMenuItem<ThemHoaDon>("Đăng Xuất", "\uf4c7", ThemHoaDon.class, false));

        //Render to UI
        menuItems.forEach(item -> {
            if(item.isBreak) { //* BREAK TITLE */
                JLabel title = new JLabel(item.title.toUpperCase());
                title.setFont(new Font("SF Pro Text", Font.BOLD, 12));
                title.setForeground(new Color(33, 43, 54));

                menuItemsGroup.add(title);
            }else{ //* MENU ITEM */
                SideBarItem menuItem = new SideBarItem();
                menuItem.setTitle(item.title);
                menuItem.setIcon(item.icon);
                menuItem.setPreferredSize(new Dimension(218, 48));

                menuItem.onClick(e -> {
                    unActiveAllMenuItem();
                    menuItem.setActive(true);

                    appContext.navigate(item.view);
                    return null;
                });

                menuItemsGroup.add(menuItem);
            }
        });
    }

    private void unActiveAllMenuItem() {
        List<Component> menuItems = new ArrayList<>();

        menuItems = Arrays.asList(menuItemsGroup.getComponents());

        menuItems.forEach(item -> {
            if(item.getClass().getSimpleName().equals("SideBarItem")) {
                SideBarItem menuItem = (SideBarItem) item;
                menuItem.setActive(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuItemsGroup = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userNameLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        appVersion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuItemsGroup.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout menuItemsGroupLayout = new javax.swing.GroupLayout(menuItemsGroup);
        menuItemsGroup.setLayout(menuItemsGroupLayout);
        menuItemsGroupLayout.setHorizontalGroup(
            menuItemsGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        menuItemsGroupLayout.setVerticalGroup(
            menuItemsGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        add(menuItemsGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 230, 600));

        jPanel1.setBackground(new java.awt.Color(234, 234, 234));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 58, 58));

        userNameLbl.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        userNameLbl.setText("USER NAME");
        jPanel1.add(userNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        emailLbl.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        emailLbl.setText("EMAIL");
        jPanel1.add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 70));

        appVersion.setFont(new java.awt.Font("Helvetica Neue", 1, 11)); // NOI18N
        appVersion.setForeground(new java.awt.Color(153, 153, 153));
        appVersion.setText("APP_VERSION");
        add(appVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appVersion;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menuItemsGroup;
    private javax.swing.JLabel userNameLbl;
    // End of variables declaration//GEN-END:variables
}
