/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package duan1.views;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

import duan1.controllers.customer.CustomerController;
import duan1.models.customer.CustomerModel;
import duan1.utils.Log;

/**
 *
 * @author TAN PHAT
 */
public class KhachHang extends View {
    //* CONTROLLERS */
    private CustomerController customerController = new CustomerController();

    //* DATA */
    private ArrayList<CustomerModel> customers = new ArrayList<>();

    /**
     * Creates new form KhachHang
     */
    public KhachHang() {
        initComponents();
        fetchData();
        init();
    }

    //* PRIVATE */
    private void init() {
        //HEADER BAR
        headerBar1.setTitle("Khách Hàng");

        //TABLE
        String[] columnNames = {"Họ Tên", "Số điện thoại", "Điểm thành viên", "Ngày tham gia"};
        Object[][] data = {};

        DefaultTableModel model = new DefaultTableModel(data, columnNames);

        customers.forEach(item -> {
            model.addRow(new Object[]{
                item.name,
                item.phone,
                item.points,
                item.dateCreated
            });
        });

        table.setModel(model);
    }

    private void fetchData() {
        try {
            customers = customerController.getAll();
        } catch (Exception e) {
            Log.error(e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        headerBar1 = new duan1.components.HeaderBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        popupMenu1.setLabel("popupMenu1");

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(819, 64));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setSize(new java.awt.Dimension(100, 64));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);
        jPanel1.add(headerBar1, java.awt.BorderLayout.LINE_START);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private duan1.components.HeaderBar headerBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
