/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package duan1.views;

import java.awt.Dimension;
import java.io.File;
import java.util.ArrayList;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import duan1.controllers.product.ManufacturerController;
import duan1.controllers.product.ProductController;
import duan1.models.product.ManufacturerModel;
import duan1.models.product.ProductModel;
import duan1.utils.Log;
import duan1.utils.NextImage;
import io.socket.client.Socket;

/**
 *
 * @author nhatsdevil
 */
public class SanPhamEdit extends javax.swing.JFrame {
    private Socket socket;
    private File productImage;

    private ManufacturerController manufacturerController = new ManufacturerController();
    private ProductController productController = new ProductController();

    private ArrayList<ManufacturerModel> manufacturers = new ArrayList<>();

    /**
     * Creates new form DimensionEdit
     */
    public SanPhamEdit() {
        initComponents();
        fetchData();
        init();
    }

    //* PUBLIC */
    public void setSocket(Socket socket) {
        this.socket = socket;
    }

    //* PRIVATE */
    private void init() {
        this.setLocationRelativeTo(null);
        this.setPreferredSize(new Dimension(810, 493));

        selectManufacturer.removeAllItems();
        manufacturers.forEach(item -> selectManufacturer.addItem(item.title));
    }

    private void fetchData() {
        //Manufacturers
        try {
            manufacturers = manufacturerController.getAll();
        } catch (Exception e) {
            Log.error(e);
        }
    }

    private void uploadImage() {
        try {
            JFileChooser fileDialog = new JFileChooser();
            fileDialog.showOpenDialog(fileDialog);

            productImage = fileDialog.getSelectedFile();

            lblImage.setIcon(new NextImage().load(productImage.getAbsolutePath(), lblImage.getWidth(), lblImage.getHeight()));
        }catch(Exception e) {
            Log.error(e);
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    private void submitProduct() {
        try {
            ProductModel product = new ProductModel();
            product.name = txtName.getText();
            product.banner = productImage.getAbsolutePath();
            product.manufacturer = manufacturers.get(selectManufacturer.getSelectedIndex())._id;
            product.releaseYear = txtReleaseDate.getText();

            //*Add to DB */
            productController.add(product);

            //*Emit to Socket
            socket.emit("/products/add", product.toJson());

            this.dispose();
        }catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            Log.error(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnExit = new duan1.components.Button();
        btnAdd = new duan1.components.Button();
        jLabel15 = new javax.swing.JLabel();
        selectManufacturer = new javax.swing.JComboBox<>();
        txtReleaseDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage.setBackground(new java.awt.Color(153, 153, 153));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("Thêm Ảnh");
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 19, 128, 128));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 280, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel6.setText("Thông Tin Cơ Bản");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel12.setText("Năm ra mắt");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel13.setText("Tên thiết bị");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        btnExit.setText("Thoát");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        btnAdd.setBackground(new java.awt.Color(0, 122, 255));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Thêm Sản Phẩm");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jLabel15.setText("Hãng sản xuất");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        selectManufacturer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(selectManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 280, -1));
        getContentPane().add(txtReleaseDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        this.uploadImage();
    }//GEN-LAST:event_lblImageMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        this.submitProduct();
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DimensionEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DimensionEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DimensionEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DimensionEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DimensionEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private duan1.components.Button btnAdd;
    private duan1.components.Button btnExit;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblImage;
    private javax.swing.JComboBox<String> selectManufacturer;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtReleaseDate;
    // End of variables declaration//GEN-END:variables
}
