/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package duan1.views;

import javax.swing.JLabel;
import javax.swing.JPanel;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.LayoutManager;
import java.io.IOException;
import java.io.InputStream;
import java.awt.FlowLayout;

import duan1.config.Config;
import duan1.utils.Log;
import duan1.utils.WrapLayout;

/**
 *
 * @author nhatsdevil
 */
public class Debug extends javax.swing.JFrame {

    /**
     * Creates new form Debug
     */
    public Debug() {
        initAssets();
        initComponents();
        redraw();
    }

    void initAssets() {
        try {
            InputStream ioniconStream = Main.class.getResourceAsStream("/duan1/assets/fonts/ionicons.ttf");
            Font ioniconsFont = Font.createFont(Font.TRUETYPE_FONT, ioniconStream);
            
            Config.FONT_IONICONS = ioniconsFont.deriveFont(Font.PLAIN, 24f);

            Log.success("[ ASSETS LOADED SUCCESSFULLY ]", Main.class.getName());
        } catch (IOException e) {
            Log.error(e);
        } catch (FontFormatException e) {
            Log.error(e);
        }
    }
    
    private void redraw() {
        JPanel panel = new JPanel();
        panel.setLayout(new FlowLayout());

        Font iconFont = Config.FONT_IONICONS.deriveFont(15f);

        for(int i = 100; i <= 399; i++) {
            JLabel iconLabel = new JLabel();
            iconLabel.setFont(iconFont);
            iconLabel.setText(Character.toChars(i).toString());

            panel.add(iconLabel);
        }

        this.add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollView = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollView, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollView, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Debug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Debug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Debug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Debug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Debug().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollView;
    // End of variables declaration//GEN-END:variables
}
