/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package duan1.views;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import duan1.controllers.user.PermissionController;
import duan1.models.user.PermissionModel;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;

/**
 *
 * @author nhatsdevil
 */
public class Permission extends View {
    PermissionEdit permissionEdit = new PermissionEdit();
    Socket socket;
    private PermissionController permissionController = new PermissionController();
    private ArrayList<PermissionModel> permissions = new ArrayList<>();
    DefaultTableModel modelTable = new DefaultTableModel();

    /**
     * Creates new form Permission
     */
    public Permission() {
        initComponents();
        init();
        fetchData();
        drawTable();
    }

    public void setSocket(Socket socket) {
        this.socket = socket;
        permissionEdit.setSocket(socket);
        this.initSocket();
    }

    private void init() {
       
    }

    private void fetchData() {
        try {
            this.permissions = permissionController.getAll();
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    private void drawTable() {
        modelTable = (DefaultTableModel) pTable.getModel();
        modelTable.setRowCount(0);

        permissions.forEach(data -> {
            modelTable.addRow(new Object[]{
                data.name
            });
        });
    }

    private void handleOpenEdit() {
        int selectedRow = pTable.getSelectedRow();

        permissionEdit.setEditData(permissions.get(selectedRow));
        permissionEdit.setVisible(true);
    }

    //*SOCKET HANDLERS */
    @Override
    public void initSocket() {
        socket.on("/permissions/add", new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                fetchData();
                drawTable();
            }
        });
        
        socket.on("/permissions/update", new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                fetchData();
                drawTable();
            }
        });
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        headerBar1 = new duan1.components.HeaderBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        pTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(819, 64));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setSize(new java.awt.Dimension(100, 64));

        btnAdd.setFont(new java.awt.Font("Ionicons", 0, 18)); // NOI18N
        btnAdd.setText("");
        btnAdd.setPreferredSize(new java.awt.Dimension(36, 36));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);
        jPanel1.add(headerBar1, java.awt.BorderLayout.LINE_START);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tên phân quyền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pTable);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        permissionEdit.setVisible(true);
    }//GEN-LAST:event_btnAddMouseClicked

    private void pTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTableMouseClicked
        this.handleOpenEdit();
    }//GEN-LAST:event_pTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private duan1.components.HeaderBar headerBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable pTable;
    // End of variables declaration//GEN-END:variables
}
