/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package duan1.views;

import java.util.ArrayList;

import org.bson.Document;

import duan1.components.Cards;
import duan1.controllers.user.UserController;
import duan1.models.user.UserModel;
import duan1.utils.Log;
import duan1.utils.WrapLayout;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;

/**
 *
 * @author nhatsdevil
 */
public class Staff extends View {
    private Socket socket;
    private StaffEdit staffEdit = new StaffEdit();

    //* CONTROLLERS */
    private UserController userController = new UserController();
    
    //* DATA */
    private ArrayList<UserModel> users = new ArrayList<UserModel>();

    /**
     * Creates new form Staff
     */
    public Staff() {
        initComponents();
        fetchData();
        init();
    }

    //* PUBLIC */
    @Override
    public void setSocket(Socket socket) {
        this.socket = socket;
        staffEdit.setSocket(socket);
        
        initSocket();
    }

    //* PRIVATE */
    private void init() {
        headerBar1.setTitle("Nhân Viên");

        drawCard();
    }

    //*SOCKET HANDLERS */
    @Override
    public void initSocket() {
        socket.on("/users/add", new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                //Update data
                UserModel user = new UserModel();
                user.fromDocument(new Document().parse((String) args[0]));;

                users.add(0, user);

                //Render card
                drawCard();
            }
        });
    }

    private void fetchData() {
        try {
            users = userController.getAll();
        }catch(Exception e) {
            Log.error(e);
        }
    }

    private void drawCard() {
        scrollView.setLayout(new WrapLayout());
        scrollView.removeAll();
        scrollView.repaint();

        users.forEach(data -> {
            Cards card = new Cards();
            card.setImg(data.avatar);
            card.setName(data.name);
            card.setPrice(0.0);
            scrollView.add(card);

            card.onClick(e -> {
                return null;

            });

        });

        scrollView.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBoder3 = new duan1.components.PanelBoder();
        jPanel4 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        headerBar1 = new duan1.components.HeaderBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        scrollView = new duan1.components.PanelBoder();

        setLayout(new java.awt.BorderLayout());

        panelBoder3.setBackground(new java.awt.Color(255, 255, 255));
        panelBoder3.setPreferredSize(new java.awt.Dimension(888, 64));
        panelBoder3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setFont(new java.awt.Font("Ionicons", 0, 18)); // NOI18N
        btnAdd.setText("");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelBoder3.add(jPanel4, java.awt.BorderLayout.LINE_END);
        panelBoder3.add(headerBar1, java.awt.BorderLayout.CENTER);

        add(panelBoder3, java.awt.BorderLayout.PAGE_START);

        scrollView.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout scrollViewLayout = new javax.swing.GroupLayout(scrollView);
        scrollView.setLayout(scrollViewLayout);
        scrollViewLayout.setHorizontalGroup(
            scrollViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        scrollViewLayout.setVerticalGroup(
            scrollViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(scrollView);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        staffEdit.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private duan1.components.HeaderBar headerBar1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private duan1.components.PanelBoder panelBoder3;
    private duan1.components.PanelBoder scrollView;
    // End of variables declaration//GEN-END:variables
}
